AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: "Python dependencies for Lambda"
      ContentUri: layer/ # ie folder layer relative to this file
      CompatibleRuntimes:
        - python3.12